version: '3'
services:
  web:
    restart: "no"
    build: ./src
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./static:/static
      - ./src:/web
    links:
      - postgres:postgres
      - redis:redis
    command: -c "while true; sleep 2; do python /web/manage.py runserver 0.0.0.0:8000; done"
    entrypoint: /bin/bash
    stdin_open: true
    tty: true

  postgres:
    restart: "no"
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    restart: "no"
    image: redis:6.2
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
